ConfVer: 1
# Версия конфигурации, с каждым обновлением будет менятся
Blocks: DIAMOND_BLOCK,DIAMOND_ORE
#Если Вы захотите сменить или добавить ещё больше блоков, то вписывайте их с запятой.

#Флаги, которые будут ставится после создания региона.
Flags:
  - tnt allow
  - pvp allow
  - greeting &7(&c!&7) Вы вошли в регион игрока &c%player%&7.
  - farewell &7(&c!&7) Вы вышли из региона игрока &c%player%&7.

#Лист флагов, которые будут доступны для использования владельцам региона. Используйте пробел и запятую, чтобы добавлять больше флагов. (Для анархии оставьте поле пустым)
Allowed Flags:

# Переключение поддержки UUID для защищенных регионов.
# ПРИМЕЧАНИЕ: Это НЕ преобразует существующий блок привата в формат UUID!! (Честно, сам нихуя не понял.)
UUID: true

#Миры где плагин не будет работать.
Worlds Denied:
    - exampleworld1
    - exampleworld2

#Основная конфигурация
  DIAMOND_BLOCK:
    X Radius: 17
    #Установите Y 0, если хотите чтобы регион был защищен с 256 блока до бедрока.
    Y Radius: 17
    Z Radius: 17
    #Прятать ли блок привата автоматически?
    Auto Hide: false
    #Отключать ли дроп блока привата после его уничтожения?
    No Drop: false
    #Поршень может двигать блок привата по умолчанию; рекомендуется ставить true если "No Drop" false, так как им можно злоупотреблять, чтобы получить больше блоков привата (дюп короче).
    Block Piston: true
    #Приоритет региона, который будет ставится по умолчанию
    Priority: 0
  DIAMOND_ORE:
    X Radius: 28
    #Установите Y 0, если хотите чтобы регион был защищен с 256 блока до бедрока.
    Y Radius: 28
    Z Radius: 28
    #Прятать ли блок привата автоматически?
    Auto Hide: false
    #Отключать ли дроп блока привата после его уничтожения?
    No Drop: false
    #Поршень может двигать блок привата по умолчанию; рекомендуется ставить true если "No Drop" false, так как им можно злоупотреблять, чтобы получить больше блоков привата (дюп короче).
    Block Piston: true
    #Приоритет региона, который будет ставится по умолчанию
    Priority: 0
  #STONE-1:    # "-1" в данной части означает блок 'гранита', который может быть использован как блок привата, но не обычный камень.
    #X Radius: 10
    #Y Radius: 10
    #Z Radius: 10
    #Auto Hide: false
    #No Drop: false
    #Block Piston: true
    #Priority: 1